stages:
- name: compile
  steps:
  - runScriptConfig:
      image: maven:3-jdk-8
      shellScript: mvn install
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-helloworld:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: 192.168.100.178:500
- name: deployment
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification:
  recipients:
  - recipient: richa@india.nec.com
    notifier: c-h8ztd:n-585k2
  condition:
  - Failed
